variables:
  DOCKER_IMAGE: ${REGISTRY_URL}/${REGISTRY_PROJECT}/${CI_PROJECT_NAME}:${CI_COMMIT_TAG}_${CI_COMMIT_SHORT_SHA}
  DOCKER_CONTAINER: ${CI_PROJECT_NAME}
stages:
  - buildandpush
  - deploy
  - checklog

build:
  stage: buildandpush
  variables:
    GIT_STRATEGY: clone
  before_script:
    - docker login ${REGISTRY_URL} -u ${REGISTRY_USER} -p ${REGISTRY_PASSWORD}
  script:
    - docker build -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE
  tags:
    - gitlab-cicd

  # only:
  #   - tags   s

deploy:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  before_script:
    - docker login ${REGISTRY_URL} -u ${REGISTRY_USER} -p ${REGISTRY_PASSWORD}
  script:
    - docker pull $DOCKER_IMAGE
    - docker rm -f $DOCKER_CONTAINER
    - docker run --name $DOCKER_CONTAINER -dp 2727:8080 $DOCKER_IMAGE
  tags:
    - gitlab-cicd
  # only:
    # - tags   
    
showlog:
  stage: checklog
  variables:
    GIT_STRATEGY: none
  script:
    - docker logs $DOCKER_CONTAINER
  tags:
    - gitlab-cicd
