name: Docker Build and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted  # Sử dụng self-hosted runner

    env:
      GIT_STRATEGY: clone  # Force a fresh clone of the repository

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0   # Ensures the full git history is pulled if needed
      - name: Ensure latest code is pulled
        run: |
          git fetch --all
          git checkout main
          git pull origin main --ff-only  # Chỉ pull nếu không có conflict
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t haianhx27/deployfe:${{ github.ref_name }}_${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push haianhx27/deployfe:${{ github.ref_name }}_${{ github.sha }}

  deploy:
    runs-on: self-hosted  # Sử dụng self-hosted runner
    needs: build
    env:
      GIT_STRATEGY: none  # Prevent fetching the source code during deploy
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker image
        run: |
          docker pull haianhx27/deployfe:${{ github.ref_name }}_${{ github.sha }}

      - name: Remove old container (if exists)
        run: |
          docker rm -f deployfe || true

      - name: Run new container
        run: |
          docker run --name deployfe -dp 3000:3000 haianhx27/deployfe:${{ github.ref_name }}_${{ github.sha }}
