name: Docker Build and Deploy

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout code from GitHub
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker registry
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.REGISTRY_URL }}/${{ secrets.REGISTRY_PROJECT }}/${{ github.event.repository.name }}:${{ github.ref_name }}_${{ github.sha }} .

      # Push Docker image to Docker registry
      - name: Push Docker image
        run: |
          docker push ${{ secrets.REGISTRY_URL }}/${{ secrets.REGISTRY_PROJECT }}/${{ github.event.repository.name }}:${{ github.ref_name }}_${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Checkout code from GitHub
      - name: Checkout code
        uses: actions/checkout@v2

      # Log in to Docker registry
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Pull Docker image
      - name: Pull Docker image
        run: |
          docker pull ${{ secrets.REGISTRY_URL }}/${{ secrets.REGISTRY_PROJECT }}/${{ github.event.repository.name }}:${{ github.ref_name }}_${{ github.sha }}

      # Stop and remove the existing container
      - name: Remove old container
        run: |
          docker rm -f ${{ github.event.repository.name }} || true

      # Run the new container
      - name: Run new container
        run: |
          docker run --name ${{ github.event.repository.name }} -dp 2727:8080 ${{ secrets.REGISTRY_URL }}/${{ secrets.REGISTRY_PROJECT }}/${{ github.event.repository.name }}:${{ github.ref_name }}_${{ github.sha }}
